### ISSUE TITLE
Бот не работает!

### ISSUE THREAD

**Issue by gODeaLoAple** [Banan-dot/Tamada#1]
Запускаю бота, а он не шутит! **_Сделайте с этим, что-нибудь!_**

**Comment by IvanSibirtsev** [comment]
нет.

**Comment by DaGnYMilleR** [comment]
Считаю, стоит внести изменения в архитектуру

**Comment by Banan-dot** [comment]
Согласен.

**Comment by DaGnYMilleR** [comment]
А подскажите, пожалуйста, как вступить в вашу организацию?

**Comment by Banan-dot** [comment]
Никак.

**Comment by DaGnYMilleR** [comment]
Прокомментируйте причину закрытия этого диалога, пожалуйста

**Comment by IvanSibirtsev** [comment]
вопрос решен.
